version: "3.4"

services:
  # Indexer
  indexer:
    container_name: indexer
    build: ./indexer
    env_file:
      - ./indexer/.env

  # RabbitMQ
  rabbitmq:
    container_name: rabbitmq
    restart: always
    tty: true
    image: rabbitmq:management
    ports:
      - 5672:5672    # standard AMQP protocol port
      - 15672:15672  # HTTP management UI
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:  # データを永続化
      - rabbitmq-data:/var/lib/rabbitmq

  # ElasticSearch
  elasticsearch:
    build: ./elasticsearch
    container_name: elasticsearch
    env_file:
      - ./elasticsearch/.env
    ports:
      - 9200:9200
    volumes:
      - elasticsearch:/var/lib/elasticsearch

volumes:
  rabbitmq-data:
    driver: local
  elasticsearch:
    driver: local